### ISSUE TITLE
カメラが機能しません

### ISSUE THREAD

**Issue by Tokutetsu** [Kai-Z-JP/KaizPatchX#100]
### Describe the bug

x,zキーを押してもズームが働かない

### To Reproduce

いつも通り起動し、シングルもしくはマルチでワールドに入り、カメラをインベントリに出し、X,Zキーを押す

### Actual Behavior

![2021-07-22_13 50 15](https://user-images.githubusercontent.com/87795690/126591584-b2b94c2e-7115-4ffc-9cf3-77413b33f10a.png)

### Screenshots

![スクリーンショット 2021-07-22 140449](https://user-images.githubusercontent.com/87795690/126592225-524afc99-339a-4e13-b85e-a8244935a5f4.png)

### OS

Windows 10 Home 21H1

### KaizPatchX Version

1.2

### Other Mods

screenshotに別記

**Comment by Kai-Z-JP** [comment]
症状を確認できませんでした。

考えられる原因としましては、ビデオ設定→臨場感ある視野角がオフになっていることが考えられます。
ご確認のほどよろしくお願いします。
