### ISSUE TITLE
[PROBLEM] The license information is not included in jar file

### ISSUE THREAD

**Issue by anatawa12** [Kai-Z-JP/KaizPatchX#103]
src1.7.10_20200822+KaizPatchX-1.2.1.jar内にもcore.jar.lzmaにもLGPLであることが書かれていません。

**Comment by Kai-Z-JP** [comment]
build.gradleの指定がLICENSEで実際のファイル名はLICENCEだったので内包されていなかったみたいです

**Comment by Kai-Z-JP** [comment]
修正しました
