### ISSUE TITLE
スクリプトが実行されない

### ISSUE THREAD

**Issue by Kai-Z-JP** [Kai-Z-JP/KaizPatchX#112]
MS932のファイルで2バイト文字を含んでいるとMac、GNU/Linuxで描画スクリプトが実行されない

KRW-ED60で確認

**Comment by anatawa12** [comment]
render関数自体は呼ばれていることを`Packages.java.lang.System.out.println("render called")`をrender関数に追加することで確認しました

**Comment by Kai-Z-JP** [comment]
描画されていないのをスクリプトが実行されていないと勘違い
