### ISSUE TITLE
[BUG] Bug overlapping rail models when replacing with RMB

### ISSUE THREAD

**Issue by MaratMadiev** [Kai-Z-JP/KaizPatchX#114]
### Describe the bug

overlapping rail models

### To Reproduce

1. Spawn a rail
2. press RMB with another type of rail

### Screenshots

![2021-07-31_02 45 02](https://user-images.githubusercontent.com/59918234/127735299-fc955a4a-69bd-4377-b3d9-b9d0bda52df2.png)
![2021-07-29_16 55 03](https://user-images.githubusercontent.com/59918234/127735300-cf4d9ca8-4bcd-4bc2-9471-71e313fe3c65.png)

### OS

windows 8.1

### KaizPatchX Version

1.3RC1.1

### Other Mods

ATSAssistMod-1.5.0

**Comment by MaratMadiev** [comment]
btw it looks pretty funny

**Comment by Kai-Z-JP** [comment]
That is not a bug.
That is a function to render the rails on top of each other ported from latest version of RTM.
If you want to replace the rail, you can do it with sneaking.

I apologize for the lack of functional explanations in non-Japanese. I will make it as soon as possible.

**Comment by MaratMadiev** [comment]
Ok, Thx
