### ISSUE TITLE
[BUG]Rail Workbench Height bug

### ISSUE THREAD

**Issue by BangRin** [Kai-Z-JP/KaizPatchX#116]
### Describe the bug

Rail WorkbenchのHeightが実行されていない (韓国語からの翻訳です。)

### To Reproduce

1.Rail Walkbenchを右クリックして路盤を雪ブロックに設定、高さを指定
2. 赤いMarkerを設置し、レールを設置
3. 下の写真のように写ります。
![2021-08-03_15 44 40](https://user-images.githubusercontent.com/63942165/127973662-91edfd08-379c-4388-8855-5cf471e097aa.png)

### Expected behavior

1.Rail Walkbenchを右クリックして路盤を雪ブロックに設定、高さを指定
2. 赤いMarkerを設置し、レールを設置
3. 下記の写真の赤い丸の結果物が欲しいです
![2021-03-22_23 05 24](https://user-images.githubusercontent.com/63942165/127973706-62354255-967b-4044-8834-712e945e4efa.png)

### OS

Window 10

### KaizPatchX Version

1.3RC1.1

### Other Mods

CustomNpc, ArchitectureCraft, ATSAssist,SignPicture

**Comment by Kai-Z-JP** [comment]
3a51a3b667a48599853358618bdb8c1f1a189de1, 8063eef0cb024fe7431ed97a9268e6832daf7a14 で修正されたはずが  83c728c6c98a24f48f87fc5b8b65f322ecdcffc2 で元に戻ってました。
再修正
