### ISSUE TITLE
[bug by fixrtm] incorrect rail switch

### ISSUE THREAD

**Issue by anatawa12** [Kai-Z-JP/KaizPatchX#124]
See also: fixrtm/fixrtm#272

### Descrive the bug

By [@272700169223405568, discord](https://discord.com/channels/749186892733480970/749187907033497601/875983167662723133)

> when i make switch like this, i have trouble
>
> ![](https://cdn.discordapp.com/attachments/749187907033497601/875983165435576320/unknown.png)
>
> (what i need)
>
> ![](https://cdn.discordapp.com/attachments/749187907033497601/875983487587479582/unknown.png)
>
> if i change marker here problem solved
> 
> ![](https://cdn.discordapp.com/attachments/749187907033497601/875984683131867156/unknown.png)

### To Reproduce

Put rail as shown this picture
![image](https://user-images.githubusercontent.com/22656849/129445537-513faf30-e472-4bc2-a19c-489d3bd58562.png)

### Expected Behavior

![](https://cdn.discordapp.com/attachments/749187907033497601/875983487587479582/unknown.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/22656849/129445544-45264ff6-30bb-403a-829c-0dbb381dce41.png)

**Comment by Kai-Z-JP** [comment]
この現象については承知しており、https://github.com/Kai-Z-JP/KaizPatchX/blob/de766c2f02907ae68c993f867a246775808fa7b0/src/main/java/jp/ngt/rtm/rail/util/SwitchType.java#L138 
を変更することで修正可能ですが、修正によってそれ以前に作成したレールの線形が変わる可能性があるため、保留しています。

**Comment by anatawa12** [comment]
ホントですね。

https://github.com/Kai-Z-JP/KaizPatchX/blob/de766c2f02907ae68c993f867a246775808fa7b0/src/main/java/jp/ngt/rtm/rail/TileEntityLargeRailSwitchCore.java#L93

こちらで使われているんですね。ありがとうございます。

**Comment by anatawa12** [comment]
For English: KaiZJP says he won't fix this issue because of the compatibility of the existing rail now.
