### ISSUE TITLE
RTM / KaizPatch not working with the Technic Launcher

### ISSUE THREAD

**Issue by Danielxs01** [Kai-Z-JP/KaizPatchX#15]
Good evening,
I got something like a question/request/enhancement.

We would like to use RTM/KaizPatch with the Technic Launcher, sadly RTM seems to be unable to load any addons.
I know, this is not really related to KaizPatch, but is there a chance someone would take a look at at that problem? ^^

Details:
Minecraft starts normal.
Everything is getting loaded, but the Loadingwindow of RTM is not opening.

The complete log:
[latest.log](https://github.com/Kai-Z-JP/KaizPatchX/files/5998497/latest.log)

Example of what happens when you try to click with a rail:
(That happens with every item that has a list)
![2021-02-17_21 45 53](https://user-images.githubusercontent.com/60752432/108265812-92015e00-7169-11eb-9c15-d80564159170.png)

If there are any questions, I will gladly reply as fast as I can.  :)

**Comment by Kai-Z-JP** [comment]
Thank you for reporting the issue.
Fixed! Please use version 1.0.4.
https://github.com/Kai-Z-JP/KaizPatchX/releases/tag/v1.0

**Comment by Danielxs01** [comment]
Thank you very much!
It works like a charm! 😄
