### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by Kai-Z-JP** [Kai-Z-JP/KaizPatchX#166]
@PC28K ko_KR.langの翻訳修正お願いできますか？

item.rtm:installedObject.{数字}.name

| 数字 | 変更前 | 変更後 | 
| -- | -- | -- |
| 0 | ガラスの蛍光灯 | 蛍光灯 |
| 1 | ダイヤの蛍光灯 | 植物 |
| 2 | 壊れた蛍光灯 |  |
| 4 | カバー付き蛍光灯 | パイプ |
| 14 |  | 架線柱 |
| 21 |  | 階段 |
| 22 |  | 足場 |

**Comment by PC28K** [comment]
やります

**Comment by PC28K** [comment]
やりました #167

**Comment by Kai-Z-JP** [comment]
ありがとうございます
