### ISSUE TITLE
Crash by NPC

### ISSUE THREAD

**Issue by Trollebas** [Kai-Z-JP/KaizPatchX#17]
[crash-2021-03-26_19_06_52-server.txt](https://github.com/Kai-Z-JP/KaizPatchX/files/6212123/crash-2021-03-26_19_06_52-server.txt)
The passenger does not work:
when issuing a ticket near the turnstile, it crashes.

**Comment by Kai-Z-JP** [comment]
Fixed in ForgeGradle-1.2 1.0.6
