### ISSUE TITLE
[機能重複]レールを変更できない

### ISSUE THREAD

**Issue by line-0707** [Kai-Z-JP/KaizPatchX#172]
### Describe the bug

例えば初期レールを水音レールに完全に変更したい場合、レールとレールの重ね合わせ機能と重複してしまい、レールを完全に変更できない

### To Reproduce

1.何でもいいからレールを適当に設置する。
2.変更したいレールを変更先レールで右クリックする。
3.レールの置き換え機能が重ね合わせ機能により機能しない

### OS

Windows10 pro 21H1

### KaizPatchX Version

1.4.0-beta2

**Comment by anatawa12** [comment]
@line-0707 スニークでレールをクリックすることで、手持ちのレールモデルを削除できるもとのレールを削除できますので、新たなレールを追加後、スニークで元のものを削除してください。

**Comment by Kai-Z-JP** [comment]
一週間たちましたので閉じさせていただきます
