### ISSUE TITLE
Crash by sleeper

### ISSUE THREAD

**Issue by Trollebas** [Kai-Z-JP/KaizPatchX#18]
[crash-2021-03-26_19_02_11-server.txt](https://github.com/Kai-Z-JP/KaizPatchX/files/6212139/crash-2021-03-26_19_02_11-server.txt)
The sleeper has stopped working:
Crashes when you bind the entity.

**Comment by Kai-Z-JP** [comment]
Fixed in ForgeGradle-1.2 1.0.6
