### ISSUE TITLE
1.16+ Version in Seperate Mod

### ISSUE THREAD

**Issue by lazytspo** [Kai-Z-JP/KaizPatchX#188]
Hi Kai-Z-JP! i would like to inform you that this mod is working for 1.7.10, alongside your other mod, fixRTM for 1.12.2. so as of suggestion, can you make a seperate mod that uses the same features than RTM 1.7.10 and 1.12.2 version, but it's going to work in 1.16 and future Minecraft versions, called "KaizPatch1.16+"? it would be nice to give you credit if you make this mod a favor and get it working on 1.16.

Thank you!

**Comment by Kai-Z-JP** [comment]
I am developing an RTM compatible FabricOpenTrains that supports 1.18+. It is a long way to complete but I will get it done. 
Thanks for your issue.
