### ISSUE TITLE
[BUG] The light is not working correctly in the render script

### ISSUE THREAD

**Issue by MaratMadiev** [Kai-Z-JP/KaizPatchX#190]
### Describe the bug

![2021-10-18_22 21 02](https://user-images.githubusercontent.com/59918234/137791363-77386c69-d21d-489a-a7eb-facfcfd9a873.png)
![2021-10-18_22 21 09](https://user-images.githubusercontent.com/59918234/137791374-3d28a16a-b46e-4254-824e-b7fa11018175.png)
In theory, the orange lamp should always be light, but when the car light is off, it uses the light0 texture, but does not shine

### To Reproduce

Use render script using pass var

### Expected behavior

The lamp shines even when the light is off

### Actual Behavior

The lamp only shines when the light is on

### OS

windows 8.1

### KaizPatchX Version

1.4RC1

**Comment by Kai-Z-JP** [comment]
This is a spec, not a bug.
xxx_light0.png(off), xxx_light1.png(headlight), xxx_light2.png(taillight)

**Comment by Kai-Z-JP** [comment]
If you want to illuminate texture, use render script
