### ISSUE TITLE
v1.4.0内のfixRTMのバージョンを2.0.20にしていただきたい

### ISSUE THREAD

**Issue by anatawa12** [Kai-Z-JP/KaizPatchX#193]
https://github.com/Kai-Z-JP/KaizPatchX/releases/tag/v1.4.0

`fixRTM(SNAPSHOT-2021-09-17-NIGHTLY以降)`のところを`fixRTM(2.0.20以降)`に変更していただきたいです

**Comment by Kai-Z-JP** [comment]
ご連絡ありがとうございます。
リリース文中内のバージョン更新いたしました。
