### ISSUE TITLE
[BUG] マーカーの分岐タイプの異常検知の範囲が広すぎる

### ISSUE THREAD

**Issue by Saqliva** [Kai-Z-JP/KaizPatchX#198]
### Describe the bug

![image](https://user-images.githubusercontent.com/65436506/142713578-4d628aec-d970-4b8e-9c67-ccdb5201e193.png)
500mくらい離れててもこうなる
マルチプレイ環境下だとユーザー同士の競合が激しいので修正求

### To Reproduce

1.複数の分岐マーカーと普通のマーカーのセットを200mくらい離して複数個置く

### OS

Windows10 21H1

### KaizPatchX Version

1.4.0

**Comment by Saqliva** [comment]
![2021-11-20_13 00 21](https://user-images.githubusercontent.com/65436506/142713783-99c6f5b5-1845-46dd-a67a-4212f58d00b1.png)

これくらい離れてても競合する
コンフィグのGeneratingDistanceは64

**Comment by Kai-Z-JP** [comment]
確認できませんでした
