### ISSUE TITLE
カスタムボタンの全車連動オプション

### ISSUE THREAD

**Issue by N1000KQ** [Kai-Z-JP/KaizPatchX#215]
カスタムボタンを全車連動できる機能が欲しいです。車番等、連動しない前提のものもあるので、ボタンごとに連動するかをjson?で設定できるようになるとありがたいです。

**Comment by Kai-Z-JP** [comment]
カスタムボタンの上にカーソルを置き、Fキーを押すことでカスタムボタンの値を全車に反映する機能を追加しました。
