### ISSUE TITLE
Offsetの指定用のアイテムをバールにする

### ISSUE THREAD

**Issue by anatawa12** [Kai-Z-JP/KaizPatchX#228]
とくにLinePole 架線柱で縦などにスニーク無しで設置できないのが使いづらいため、同じアイテムでクリックではなくバールでクリックすることでoffseetを指定するためのGUIを開くのを提案します。

fixRTMへの移植中(fixrtm/fixRTM#416)に不便だと思い、KaizPatchXでの動作はバージョンa093ac9で確認しました。

**Comment by Kai-Z-JP** [comment]
確認しました。こちらにも実装します。ありがとうございます。
