### ISSUE TITLE
[REQUEST] Port this to 1.12.2 version

### ISSUE THREAD

**Issue by choonsik32** [Kai-Z-JP/KaizPatchX#251]
### Describe the bug

I play with 1.12.2 version modpack and rtm of 1.12.2 is buggy and not stable 
I request to port this pack pack to 1.12.2 version

### To Reproduce

port it

### OS

Window 10 

### KaizPatchX Version

1.0.0

**Comment by Kai-Z-JP** [comment]
It's been a week now, so I'm closing it.
