### ISSUE TITLE
[BUG] オフセットの設定ができない

### ISSUE THREAD

**Issue by PC28K** [Kai-Z-JP/KaizPatchX#270]
### Describe the bug

1.5.0betaでオフセットの設定ができない

### To Reproduce

コネクターを設置してコネクターで右クリックしてもRSほこりが出るだけでオフセット窓が出てこない
コネクター以外他(照明など)も同じ

同じ環境で1.4.6ならできる

### OS

win10pro

### KaizPatchX Version

1.5.0 beta1

**Comment by Kai-Z-JP** [comment]
今バージョンからの仕様です
オフセットの設定用アイテムをバールに統一しました

**Comment by PC28K** [comment]
あっ
