### ISSUE TITLE
[BUG] sound_BrakeReleaseなどが運転してる車両でしか鳴らない

### ISSUE THREAD

**Issue by PC28K** [Kai-Z-JP/KaizPatchX#284]
### Describe the bug

sound_BrakeRelease、sound_BrakeRelease2が運転してる車両でしか鳴らない

### To Reproduce

車を何両か繋いで運転して見るとそうなる

### Expected behavior

編成全車で音が鳴る

### OS

win10pro

### KaizPatchX Version

1.5.0

**Comment by Kai-Z-JP** [comment]
ControlCarでしか鳴らないようになってるから実装は正しい

**Comment by PC28K** [comment]
その実装になんか理由があるんですか?

**Comment by Kai-Z-JP** [comment]
EntityTrainBaseに実装の機能でそもそもノッチがControlCarにしか設定されないからだと思う普通にFormationEntryで回せばなんとかなるから修正する2022/07/15 15:20 PC28K ***@***.***>:

その実装になんか理由があるんですか?

**Comment by Kai-Z-JP** [comment]
EntityTrainBaseに実装の機能でそもそもノッチがControlCarにしか設定されないからだと思う
普通にFormationEntryで回せばなんとかなるから修正する
