### ISSUE TITLE
不明なエラー

### ISSUE THREAD

**Issue by YCT01S** [Kai-Z-JP/KaizPatchX#287]
### Describe the bug

オリジナルRTMのアーカイブを開くとゲームがクラッシュしました
（ソフトウェア翻訳を使っています）

### To Reproduce

1.オリジナルRTMアーカイブのインポート
2.プレイヤーがある位置に移動した後にゲームがクラッシュする
（カーブと関係がありますか？）

### Expected behavior

他に予想される行動はなかった

### Actual Behavior

https://user-images.githubusercontent.com/109348244/179319282-3f07e037-f38d-4465-82c2-db001e84cb33.mp4

https://user-images.githubusercontent.com/109348244/179319252-c7a968f2-e459-445a-bf9d-c0e520281cd6.mp4

### Screenshots

ゲームクラッシュ地点
![2022-07-15_21 23 38](https://user-images.githubusercontent.com/109348244/179233759-bde03fb1-c537-4c0e-a83d-2ed5f05b598e.png)
![2022-07-15_21 24 42](https://user-images.githubusercontent.com/109348244/179236729-7777fd9a-3126-473c-a156-801ab6458c64.png)

### Crash Reports

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 22-7-15 下午5:51
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at jp.ngt.rtm.rail.util.RailMapBasic.getLength(RailMapBasic.java:112)
	at jp.ngt.rtm.render.RailPartsRenderer.createRailPos(RailPartsRenderer.java:147)
	at jp.ngt.rtm.render.RailPartsRenderer.renderStaticParts(RailPartsRenderer.java:106)
	at jdk.nashorn.internal.scripts.Script$Recompilation$2783$943AAAAAA$\^eval\_.renderRailStatic(<eval>:25)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:649)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at jp.ngt.ngtlib.io.ScriptUtil.doScriptFunction(ScriptUtil.java:58)
	at jp.ngt.rtm.render.RailPartsRenderer.renderRailStatic(RailPartsRenderer.java:58)
	at jp.ngt.rtm.render.RailPartsRenderer.renderRail(RailPartsRenderer.java:47)
	at jp.ngt.rtm.rail.RenderLargeRail.renderTileEntityLargeRail(RenderLargeRail.java:39)
	at jp.ngt.rtm.rail.RenderLargeRail.func_147500_a(RenderLargeRail.java:24)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:807)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1712)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at jp.ngt.rtm.rail.util.RailMapBasic.getLength(RailMapBasic.java:112)
	at jp.ngt.rtm.render.RailPartsRenderer.createRailPos(RailPartsRenderer.java:147)
	at jp.ngt.rtm.render.RailPartsRenderer.renderStaticParts(RailPartsRenderer.java:106)
	at jdk.nashorn.internal.scripts.Script$Recompilation$2783$943AAAAAA$\^eval\_.renderRailStatic(<eval>:25)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:649)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at jp.ngt.ngtlib.io.ScriptUtil.doScriptFunction(ScriptUtil.java:58)
	at jp.ngt.rtm.render.RailPartsRenderer.renderRailStatic(RailPartsRenderer.java:58)
	at jp.ngt.rtm.render.RailPartsRenderer.renderRail(RailPartsRenderer.java:47)
	at jp.ngt.rtm.rail.RenderLargeRail.renderTileEntityLargeRail(RenderLargeRail.java:39)
	at jp.ngt.rtm.rail.RenderLargeRail.func_147500_a(RenderLargeRail.java:24)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)

-- Block Entity Details --
Details:
	Name: TERailSlopeCore // jp.ngt.rtm.rail.TileEntityLargeRailSlopeCore
	Block type: ID #526 (tile.rtm:LRLCore // jp.ngt.rtm.rail.BlockLargeRailSlopeCore)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (254,73,-268), Chunk: (at 14,4,4 in 15,-17; contains blocks 240,0,-272 to 255,255,-257), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #526 (tile.rtm:LRLCore // jp.ngt.rtm.rail.BlockLargeRailSlopeCore)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:807)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1712)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['ymt01'/248, l='MpServer', x=226.67, y=76.75, z=-419.46]]
	Chunk stats: MultiplayerChunkCache: 609, 618
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-48,64,436), Chunk: (at 0,4,4 in -3,27; contains blocks -48,0,432 to -33,255,447), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 18051568 game time, 97800 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 122 total; [EntityClientPlayerMP['ymt01'/248, l='MpServer', x=226.67, y=76.75, z=-419.46], EntityTrain['entity.RTM.RTM.E.Train.name'/2053, l='MpServer', x=221.45, y=75.25, z=-425.97], EntityBogie['entity.RTM.RTM.E.Bogie.name'/2054, l='MpServer', x=225.10, y=75.25, z=-420.30], EntityBogie['entity.RTM.RTM.E.Bogie.name'/2055, l='MpServer', x=217.59, y=75.25, z=-431.95], EntityFloor['entity.RTM.RTM.E.Floor.name'/2059, l='MpServer', x=225.06, y=75.24, z=-421.75], EntityFloor['entity.RTM.RTM.E.Floor.name'/2060, l='MpServer', x=224.52, y=75.24, z=-422.59], EntityFloor['entity.RTM.RTM.E.Floor.name'/2061, l='MpServer', x=223.98, y=75.24, z=-423.43], EntityFloor['entity.RTM.RTM.E.Floor.name'/2062, l='MpServer', x=223.43, y=75.24, z=-424.27], EntityFloor['entity.RTM.RTM.E.Floor.name'/2063, l='MpServer', x=222.89, y=75.24, z=-425.11], EntityFloor['entity.RTM.RTM.E.Floor.name'/2064, l='MpServer', x=219.37, y=75.24, z=-430.58], EntityFloor['entity.RTM.RTM.E.Floor.name'/2065, l='MpServer', x=219.91, y=75.24, z=-429.74], EntityFloor['entity.RTM.RTM.E.Floor.name'/2066, l='MpServer', x=220.45, y=75.24, z=-428.90], EntityFloor['entity.RTM.RTM.E.Floor.name'/2067, l='MpServer', x=220.99, y=75.24, z=-428.06], EntityFloor['entity.RTM.RTM.E.Floor.name'/2068, l='MpServer', x=221.54, y=75.24, z=-427.22], EntityFloor['entity.RTM.RTM.E.Floor.name'/2069, l='MpServer', x=223.80, y=75.26, z=-420.94], EntityFloor['entity.RTM.RTM.E.Floor.name'/2070, l='MpServer', x=223.26, y=75.26, z=-421.78], EntityFloor['entity.RTM.RTM.E.Floor.name'/2071, l='MpServer', x=222.72, y=75.26, z=-422.62], EntityFloor['entity.RTM.RTM.E.Floor.name'/2072, l='MpServer', x=222.17, y=75.26, z=-423.46], EntityFloor['entity.RTM.RTM.E.Floor.name'/2073, l='MpServer', x=221.63, y=75.26, z=-424.30], EntityFloor['entity.RTM.RTM.E.Floor.name'/2074, l='MpServer', x=218.11, y=75.26, z=-429.76], EntityFloor['entity.RTM.RTM.E.Floor.name'/2075, l='MpServer', x=218.65, y=75.26, z=-428.92], EntityFloor['entity.RTM.RTM.E.Floor.name'/2076, l='MpServer', x=219.19, y=75.26, z=-428.08], EntityFloor['entity.RTM.RTM.E.Floor.name'/2077, l='MpServer', x=219.73, y=75.26, z=-427.24], EntityFloor['entity.RTM.RTM.E.Floor.name'/2078, l='MpServer', x=220.28, y=75.26, z=-426.40], EntityPig['猪'/2128, l='MpServer', x=333.22, y=127.00, z=-548.03], EntityPig['猪'/2129, l='MpServer', x=335.88, y=126.00, z=-546.50], EntityPig['猪'/2130, l='MpServer', x=335.34, y=116.00, z=-549.41], EntityPig['猪'/2131, l='MpServer', x=322.94, y=71.00, z=-464.41], EntityPig['猪'/2133, l='MpServer', x=333.31, y=70.00, z=-454.53], EntityPig['猪'/2134, l='MpServer', x=331.50, y=70.00, z=-454.53], EntityPig['猪'/2135, l='MpServer', x=332.66, y=82.00, z=-463.06], EntityPig['猪'/2136, l='MpServer', x=329.34, y=63.00, z=-434.19], EntityPig['猪'/2137, l='MpServer', x=327.28, y=63.00, z=-436.81], EntityPig['猪'/2138, l='MpServer', x=335.84, y=67.00, z=-309.59], EntityPig['猪'/2139, l='MpServer', x=330.88, y=66.00, z=-314.84], EntityPig['猪'/2151, l='MpServer', x=81.34, y=68.00, z=-303.84], EntityPig['猪'/2152, l='MpServer', x=182.09, y=64.00, z=-297.94], EntityPig['猪'/2153, l='MpServer', x=319.88, y=88.00, z=-291.84], EntityPig['猪'/2165, l='MpServer', x=336.47, y=114.00, z=-545.53], EntityPig['猪'/2166, l='MpServer', x=350.03, y=65.00, z=-454.72], EntityPig['猪'/2167, l='MpServer', x=346.81, y=64.00, z=-389.88], EntityPig['猪'/2168, l='MpServer', x=343.94, y=64.00, z=-384.75], EntityPig['猪'/2169, l='MpServer', x=348.09, y=64.00, z=-384.03], EntityPig['猪'/2170, l='MpServer', x=336.53, y=66.00, z=-384.31], EntityPig['猪'/2171, l='MpServer', x=349.47, y=69.00, z=-301.34], EntityPig['猪'/915, l='MpServer', x=227.69, y=64.00, z=-389.56], EntityPig['猪'/916, l='MpServer', x=231.03, y=64.00, z=-564.81], EntityMinecartChest['entity.MinecartChest.name'/917, l='MpServer', x=150.50, y=40.50, z=-393.50], EntityMinecartChest['entity.MinecartChest.name'/918, l='MpServer', x=170.50, y=39.50, z=-411.50], EntityMinecartChest['entity.MinecartChest.name'/919, l='MpServer', x=142.50, y=42.50, z=-436.50], EntityPig['猪'/920, l='MpServer', x=196.97, y=66.00, z=-371.91], EntityPig['猪'/921, l='MpServer', x=189.91, y=68.00, z=-402.94], EntityChicken['鸡'/922, l='MpServer', x=215.44, y=64.00, z=-414.44], EntityPig['猪'/923, l='MpServer', x=236.59, y=66.00, z=-534.91], EntityPig['猪'/924, l='MpServer', x=252.41, y=64.00, z=-555.78], EntityPig['猪'/925, l='MpServer', x=248.78, y=64.00, z=-559.25], EntityMinecartChest['entity.MinecartChest.name'/926, l='MpServer', x=160.50, y=46.50, z=-378.50], EntityMinecartChest['entity.MinecartChest.name'/927, l='MpServer', x=160.50, y=39.50, z=-396.50], EntityMinecartChest['entity.MinecartChest.name'/928, l='MpServer', x=174.50, y=41.50, z=-448.50], EntityPig['猪'/929, l='MpServer', x=168.22, y=63.00, z=-463.94], EntityMinecartChest['entity.MinecartChest.name'/930, l='MpServer', x=183.50, y=30.50, z=-372.50], EntityMinecartChest['entity.MinecartChest.name'/931, l='MpServer', x=180.50, y=42.50, z=-370.50], EntityPig['猪'/2222, l='MpServer', x=354.53, y=89.00, z=-530.78], EntityPig['猪'/2223, l='MpServer', x=356.22, y=85.00, z=-528.53], EntityPig['猪'/2224, l='MpServer', x=352.34, y=95.00, z=-534.22], EntityPig['猪'/2225, l='MpServer', x=357.38, y=79.00, z=-523.16], EntityPig['猪'/2226, l='MpServer', x=352.34, y=64.00, z=-450.13], EntityPig['猪'/2227, l='MpServer', x=352.88, y=64.00, z=-452.16], EntitySheep['羊'/2232, l='MpServer', x=126.06, y=68.00, z=-286.94], EntitySheep['羊'/2233, l='MpServer', x=125.06, y=69.00, z=-276.94], EntityPig['猪'/2234, l='MpServer', x=174.84, y=66.00, z=-274.06], EntityPig['猪'/2235, l='MpServer', x=194.91, y=64.00, z=-287.19], EntityPig['猪'/956, l='MpServer', x=114.34, y=70.00, z=-313.53], EntityPig['猪'/2236, l='MpServer', x=227.66, y=61.00, z=-286.53], EntityMinecartChest['entity.MinecartChest.name'/957, l='MpServer', x=148.50, y=38.50, z=-364.50], EntityPig['猪'/2237, l='MpServer', x=350.97, y=69.00, z=-276.63], EntityPig['猪'/958, l='MpServer', x=147.09, y=67.00, z=-364.22], EntityPig['猪'/959, l='MpServer', x=159.94, y=65.00, z=-338.03], EntityPig['猪'/960, l='MpServer', x=157.06, y=65.00, z=-323.94], EntityMinecartChest['entity.MinecartChest.name'/961, l='MpServer', x=188.50, y=36.50, z=-356.50], EntityPig['猪'/962, l='MpServer', x=201.88, y=66.00, z=-352.78], EntityPig['猪'/963, l='MpServer', x=200.56, y=68.00, z=-330.75], EntityPig['猪'/964, l='MpServer', x=220.22, y=65.00, z=-359.16], EntityChicken['鸡'/965, l='MpServer', x=209.44, y=67.00, z=-323.03], EntityPig['猪'/967, l='MpServer', x=237.81, y=65.00, z=-365.78], EntityPig['猪'/968, l='MpServer', x=237.09, y=64.00, z=-316.31], EntityPig['猪'/969, l='MpServer', x=233.09, y=64.00, z=-307.25], EntityPig['猪'/2255, l='MpServer', x=378.59, y=92.00, z=-546.59], EntityPig['猪'/2256, l='MpServer', x=372.53, y=93.00, z=-543.28], EntityPig['猪'/977, l='MpServer', x=258.97, y=64.00, z=-322.03], EntityPig['猪'/2257, l='MpServer', x=372.47, y=97.00, z=-536.75], EntityPig['猪'/2258, l='MpServer', x=373.97, y=98.00, z=-535.38], EntityChicken['鸡'/2259, l='MpServer', x=382.53, y=63.00, z=-414.56], EntityChicken['鸡'/2260, l='MpServer', x=382.19, y=63.00, z=-405.22], EntityChicken['鸡'/2261, l='MpServer', x=383.22, y=64.00, z=-312.78], EntityPig['猪'/982, l='MpServer', x=280.91, y=65.00, z=-373.91], EntityPig['猪'/983, l='MpServer', x=286.94, y=66.00, z=-325.19], EntityPig['猪'/990, l='MpServer', x=301.56, y=68.00, z=-582.47], EntityPig['猪'/991, l='MpServer', x=302.50, y=123.00, z=-547.50], EntityPig['猪'/992, l='MpServer', x=302.44, y=135.00, z=-549.53], EntityPig['猪'/993, l='MpServer', x=296.53, y=63.00, z=-452.34], EntityPig['猪'/994, l='MpServer', x=300.09, y=64.00, z=-454.75], EntityChicken['鸡'/995, l='MpServer', x=296.53, y=66.00, z=-336.53], EntitySheep['羊'/2275, l='MpServer', x=148.03, y=68.00, z=-265.94], EntityPig['猪'/2277, l='MpServer', x=187.84, y=64.00, z=-266.84], EntityChicken['鸡'/2278, l='MpServer', x=201.53, y=64.00, z=-266.94], EntityPig['猪'/999, l='MpServer', x=312.53, y=66.00, z=-582.28], EntityChicken['鸡'/2279, l='MpServer', x=212.44, y=63.00, z=-263.91], EntityPig['猪'/2280, l='MpServer', x=219.94, y=63.00, z=-266.38], EntityPig['猪'/1001, l='MpServer', x=306.50, y=128.00, z=-545.50], EntityPig['猪'/1002, l='MpServer', x=304.47, y=138.00, z=-547.56], EntityPig['猪'/1003, l='MpServer', x=319.19, y=70.00, z=-467.06], EntityPig['猪'/1004, l='MpServer', x=304.53, y=63.00, z=-459.47], EntityPig['猪'/1005, l='MpServer', x=304.72, y=63.00, z=-461.91], EntityPig['猪'/1006, l='MpServer', x=319.09, y=63.00, z=-440.94], EntityPig['猪'/1007, l='MpServer', x=315.84, y=63.00, z=-435.31], EntityPig['猪'/1008, l='MpServer', x=315.91, y=64.00, z=-442.88], EntityPig['猪'/1009, l='MpServer', x=313.19, y=63.00, z=-431.84], EntityPig['猪'/1010, l='MpServer', x=305.28, y=63.00, z=-428.84], EntityPig['猪'/1011, l='MpServer', x=316.56, y=65.00, z=-380.50], EntityChicken['鸡'/1012, l='MpServer', x=308.13, y=66.00, z=-372.16], EntityPig['猪'/1013, l='MpServer', x=306.94, y=67.00, z=-328.94]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 348719024 bytes (332 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx2048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	OpenEye{0.8} [OpenEye] (OpenEye.jar) 
	UCHIJAAAA	TooManyItems{1.7.10[hukk汉化]} [TooManyItems] (minecraft.jar) 
	UCHIJAAAA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	fullbright{1.2} [Fullbright] (1.7.10-Fullbright-v1.2.jar) 
	UCHIJAAAA	cfm{3.4.7} [?9MrCrayfish's Furniture Mod] ([MrCrayfish 的家具] MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	Waila{1.5.8} [Waila] ([NEI扩展]Waila-1.5.9_1.7.10.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] ([R键整理] InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] ([创世神] worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] ([工业时代2] industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAA	flammpfeil.slashblade{mc1.7.10-r87} [SlashBlade] ([拔刀剑] SlashBlade-mc1.7.10-r87.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.10.1} [ProjectE] ([等价交换重制版] ProjectE-1.7.10-PE1.10.1.jar) 
	UCHIJAAAA	mobends{0.20.1} [Mo' Bends] (bd127717.zip) 
	UCHIJAAAA	craftguide{1.7.1.0} [CraftGuide] (CraftGuide-1.7.1.0-forge.jar) 
	UCHIJAAAA	erde{1.0c} [Entity Render Extender] (EntityRenderDistanceExtender-1.0c.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (mckuai1.7.10Custom-NPCs-Mod.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (mckuai1.7.10malisisdoorsmod.jar) 
	UCHIJAAAA	MESLRL{1.7.10_1.0} [MESL Re-Launcher] (MhnElecSoundlib.zip) 
	UCHIJAAAA	roadstuff{1.0.3-final} [Road Stuff] (RoadStuff-mc1.7.10-1.0.2-final.jar) 
	UCHIJAAAA	NGTLib{1.7.10.32} [NGTLib] (src1.7.10_20200822 KaizPatchX-1.5.0.jar) 
	UCHIJAAAA	MCTE{1.7.10.16} [MCTerrainEditor] (src1.7.10_20200822 KaizPatchX-1.5.0.jar) 
	UCHIJAAAA	RTM{1.7.10.41_KaizPatchX1.5.0} [RealTrainMod] (src1.7.10_20200822 KaizPatchX-1.5.0.jar) 
	UCHIJAAAA	stationsMod{1.7.10.5} [Stations Mod] (StationsMod-1.7.10.5汉化.jar) 
	Launched Version: 1.7.10-Forge 10.13.4.1614-LiteLoader-OptiFine_E7
	LWJGL: 2.9.1
	OpenGL: GeForce 930MX/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [§8!%3!§bDynamic Duo §8blue.zip, Dramatic+Skys+Demo+1.4.zip, PCL2 Skin.zip]
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

### OS

Windows 10 pro

### KaizPatchX Version

1.5.0

### Other Mods

Stationsmod

**Comment by Kai-Z-JP** [comment]
修正しました

**Comment by Kai-Z-JP** [comment]
Fixed in [v1.5.1](https://github.com/Kai-Z-JP/KaizPatchX/releases/tag/v1.5.1) Please try it.
