### ISSUE TITLE
[BUG]ブロックレンダリングの問題

### ISSUE THREAD

**Issue by YCT01S** [Kai-Z-JP/KaizPatchX#292]
### Describe the bug

不明

### To Reproduce

不明

### Crash Reports

[crash-2022-07-25_13.12.06-server.txt](https://github.com/Kai-Z-JP/KaizPatchX/files/9178214/crash-2022-07-25_13.12.06-server.txt)
[crash-2022-07-25_13.07.15-server.txt](https://github.com/Kai-Z-JP/KaizPatchX/files/9178217/crash-2022-07-25_13.07.15-server.txt)

### OS

Windows 10 pro

### KaizPatchX Version

1.5.1

**Comment by Kai-Z-JP** [comment]
恐らくRTM系の問題ではないため、閉じさせていただきます。
