### ISSUE TITLE
[BUG]　キーボードで次の/前の放送にすると放送がNULLに

### ISSUE THREAD

**Issue by PC28K** [Kai-Z-JP/KaizPatchX#302]
### Describe the bug

nullになる
たぶん

if(これ==最後のやつ)　いやだ

みたいな処理がないのかな　と思います

### To Reproduce

・一番目の放送が選択されているときにキーボード←するとnullになる
・最後の放送が選択されているときにキーボード→するとnullになる

### OS

win10pro

### KaizPatchX Version

1.5.2

**Comment by Kai-Z-JP** [comment]
直します

**Comment by Kai-Z-JP** [comment]
解決
