### ISSUE TITLE
RailMap versioning System

### ISSUE THREAD

**Issue by Kai-Z-JP** [Kai-Z-JP/KaizPatchX#317]
https://github.com/fixrtm/fixRTM/issues/560

互換性維持のために修正ができなかった線形問題(https://github.com/Kai-Z-JP/KaizPatchX/issues/124 など)をRailMapへのバージョン付与によって解決

**Comment by anatawa12** [comment]
fixRTM/fixRTM#560 ですね

**Comment by Kai-Z-JP** [comment]
ありがとうございます 修正しました
