### ISSUE TITLE
運転手がだせない

### ISSUE THREAD

**Issue by Hachiko-Special-Rapid** [Kai-Z-JP/KaizPatchX#320]
### Describe the bug

MOBの運転手が出せません
出したら一瞬で消えます

### To Reproduce

運転手を出すもしくは車両に乗せる

### OS

Windows10

### KaizPatchX Version

1.6.0-rc2

**Comment by Kai-Z-JP** [comment]
症状を確認できませんでした。
他の導入ModやSMPかシングルかなど詳しい環境を記載してください。
![image](https://user-images.githubusercontent.com/42648535/198741374-a0c91a22-3386-4541-82c1-026c96684c8a.png)

**Comment by Hachiko-Special-Rapid** [comment]
Bamboo-2.6.8.5
StationsMod-1.7.10.3
UpToDateMod 2.3.11
WorldEdit 6.1.1
SoundLimitExtends 1.0
SignalControllerMOD 1.4.0
Dimensional Anchors 59.0.3
Immibis Core 59.1.4
ATSAssist 1.7.4
EntityRenderDisrtanceExtrand-1.0c

クリエイティブマルチ

Forge鯖

**Comment by Hachiko-Special-Rapid** [comment]
https://twitter.com/Hachiko_Server/status/1586286469747855360

**Comment by Kai-Z-JP** [comment]
動画を見た限りでは、Modのバグと言うよりもMinecraft/Bukkit/ForgeでのMobスポーンを禁止する設定が原因に思われます。

**Comment by Kai-Z-JP** [comment]
一週間経過したので閉じさせていただきます
