### ISSUE TITLE
幕、車内放送のプルダウン式選択の実装

### ISSUE THREAD

**Issue by MilkNum2** [Kai-Z-JP/KaizPatchX#324]
### Feature report check list

- [x] 非正式版を含む最新のバージョンの KaizPatchX にその機能が存在しないこと
- [x] issues でそのリクエストがまだ無いこと。

### Describe the feature

幕、車内放送のgui上の選択をより楽にする方法として提案させていただきます

**Comment by Kai-Z-JP** [comment]
![image](https://user-images.githubusercontent.com/42648535/200156427-530db2e4-2d3c-4bc0-b0c7-21fed4270874.png)
