### ISSUE TITLE
[BUG]幕設定が違う車両同士の併結、置き換え時のクラッシュ

### ISSUE THREAD

**Issue by MilkNum2** [Kai-Z-JP/KaizPatchX#354]
### Describe the bug

rollsignが統一されていない車両同士を併結した
またはrollsign設定が違う車両をモデル置き換えにより置き換えた場合に車両のSettings（バールマーク）を開くとクラッシュが発生する

### To Reproduce

車両を用意する
↓
モデル置き換えでrollsign設定が違う電車に置き換える または rollsign設定の違う電車と併結
↓
Settingsを開くとクラッシュ

### Expected behavior

gui関連でクラッシュレポートが出ているため、プルダウン実装によるものと思われます

### Crash Reports

`

### OS

macOS 11.0.1 / Windows 10

### KaizPatchX Version

1.6.2

**Comment by Kai-Z-JP** [comment]
#350 で修正済み
