### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by detteyuu** [Kai-Z-JP/KaizPatchX#358]
### Describe the bug

エディターで選択したままクリアせずにワールドを抜けると選択できなくなる問題（もう1度クリアしても無理）

### To Reproduce

エディターで選択します
ワールドを抜けます
詰みます

### OS

macOS ventura 13.0.1(22A400)

### KaizPatchX Version

1.6.6

**Comment by Kai-Z-JP** [comment]
#353 で修正済みです
