### ISSUE TITLE
[BUG]照明ブロックなどがオフセットできない

### ISSUE THREAD

**Issue by tokaido-233** [Kai-Z-JP/KaizPatchX#372]
### Describe the bug

Kaizpatch 1.6.2で、照明ブロックや標識等がオフセットできないバグです。

### To Reproduce

1.照明等過去のバージョンでオフセットできたブロックをシフト右クリックする。

### OS

Windows11

### KaizPatchX Version

1.6.2

**Comment by Kai-Z-JP** [comment]
バールで右クリックしてください

**Comment by tokaido-233** [comment]
いつの間に仕様変更してたんですね
勘違いすいません&ありがとうございます
