### ISSUE TITLE
[BUG]照明モデルが上手く描画されない。

### ISSUE THREAD

**Issue by otokawarailway** [Kai-Z-JP/KaizPatchX#373]
### Describe the bug

照明モデルにおいて、設置マスが画面外に行くとモデルが描画されなくなります。

### To Reproduce

1. 2×2以上の照明モデルを設置する。
2. 設置したマスを画面外にする。
3. モデルが描画されなくなる。
4. 設置したマスを画面外に戻すと、再び描画される。

### Screenshots

![2023-03-02_12 23 43](https://user-images.githubusercontent.com/103886907/222324691-c4771ea8-b9a4-43b7-814a-b57451df5ae3.png)
![2023-03-02_12 23 38](https://user-images.githubusercontent.com/103886907/222324695-e7628e31-4568-4f63-b320-56217c7e66d8.png)

### OS

windows11

### KaizPatchX Version

1.7.0-beta.1

**Comment by Kai-Z-JP** [comment]
1.7.0-beta.1より描画負荷の対策のため、RenderAABBが設定されていない場合の描画範囲を1x1に変更したためです。モデルのコンフィグにRenderAABBを[-2, -3, 0, 3, 1, 1](メタセコでのモデルの方向に依ります)などに設定することで、指定した描画範囲内へ視線が向いているときに描画がされるようになります。

**Comment by Kai-Z-JP** [comment]
一週間たちましたので閉じさせていただきます
