### ISSUE TITLE
レバーサーが後ろと前の車両を連結させると変になる

### ISSUE THREAD

**Issue by line-0707** [Kai-Z-JP/KaizPatchX#38]
レバーサーが前になっている車両にレバーサー後ろにした車両を後退しながら連結させ、レバーサーを前にして運転すると動作がおかしくなる

**Comment by Kai-Z-JP** [comment]
調査中

**Comment by Kai-Z-JP** [comment]
こちらでは症状を再現できませんでした。
どのような場合になるのかを具体的に記載お願いします。
ex.サーバーかクライアントか 前後の編成の両数 どのように変になるか

**Comment by Kai-Z-JP** [comment]
#51 で修正されました。
