### ISSUE TITLE
[BUG]車両レンダリングが不完全です

### ISSUE THREAD

**Issue by YCT01S** [Kai-Z-JP/KaizPatchX#382]
### Describe the bug

KaizPatchXでは、スクリプトを含む一部の車両が正常にレンダリングされない
（ソフトウェア翻訳を使っています）

### To Reproduce

下図のように、この車はオリジナルのRTMでは正常です
https://user-images.githubusercontent.com/109348244/229286342-c5ac8e6c-46b0-4373-9347-9e649ba70364.png
スクリプトのため、KaizPatchXでボディの一部をレンダリングできませんでした
https://user-images.githubusercontent.com/109348244/229286473-44c6258a-9a59-4d25-b0c4-6e7b3b7e9db1.png
追加パックはこちら（テスト用のみ、問題解決後はダウンロードリンクを閉じます）
https://share.weiyun.com/l4p1o7rn

### OS

Windows 10 pro 21H2

### KaizPatchX Version

1.6.2

**Comment by YCT01S** [comment]
https://share.weiyun.com/cWQ12hZt

**Comment by Kai-Z-JP** [comment]
please change path of ebtf_mat2 in "assets\minecraft\models\ST01Mc.mqo" to ..\textures\train\ST01\TICS.png.
Character of your user name is not defined in S-JIS(MS932).
