### ISSUE TITLE
[BUG FROM FIXRTM] If we changed key configuration to mouse events, It may not be works.

### ISSUE THREAD

**Issue by anatawa12** [Kai-Z-JP/KaizPatchX#40]
ORIGINAL ISSUE: https://github.com/fixrtm/fixRTM/issues/212

設定でRTMの操作に関わるキーをマウスに変更すると、動かないようです。

fixrtm/fixRTM@21233b21235069c797f3a2233d1239a6616c587e 
こちらのようにKeyInputEventからInputEventに変更すると問題なく動くようです

https://github.com/Kai-Z-JP/KaizPatchX/blob/216aba143a88f6f1fa929bf20128e92ab10a7824/src/main/java/jp/ngt/rtm/event/RTMKeyHandlerClient.java#L98

![image](https://user-images.githubusercontent.com/22656849/118666313-0a8dbe80-b82e-11eb-90f2-5eccb25ca896.png)
![image](https://user-images.githubusercontent.com/22656849/118666322-0c578200-b82e-11eb-9298-bc1d50a55af2.png)

**Comment by Kai-Z-JP** [comment]
感謝します
