### ISSUE TITLE
地上子の描画範囲変更

### ISSUE THREAD

**Issue by N1000KQ** [Kai-Z-JP/KaizPatchX#407]
### Feature report check list

- [X] 非正式版を含む最新のバージョンの KaizPatchX にその機能が存在しないこと
- [X] issues でそのリクエストがまだ無いこと。

### Describe the feature

提案内容) 地上子をより遠くから描画できるようにする

現状だと40mくらいまで近づかないと描画されませんが、地上子(列車検知器 or ATC)モデルの停車目標など遠くから視認したい場合があるので提案いたします。

**Comment by Kai-Z-JP** [comment]
どれくらいがいいですか？

**Comment by Kai-Z-JP** [comment]
現状64なのですが、10倍ぐらいあれば良いですか?
