### ISSUE TITLE
[BUG]加速度/減速度カスタムが変です

### ISSUE THREAD

**Issue by PC28K** [Kai-Z-JP/KaizPatchX#42]
**再現手順**
動作を再現する手順:
```
"accelerateion": 0.00249984,
"maxSpeed": [0.41, 0.62, 0.96, 1.38],
"accelerateions": [0.00124992, 0.0020, 0.00249984, 0.00249984],
"deccelerations": [0, -0.0003, -0.0007, -0.0010, -0.0014, -0.0017, -0.0020, -0.0024, -0.0031],
"notDisplayCab": true,
```
こうしたら
 - 加速度/減速度カスタムしてる場合、(例え) P1で30、P4で100まで加速できるとしたら P4で30以上まで加速してP1に下げても速力が変わらない
 - -0(N)にしても速力が下がらない
https://www.youtube.com/watch?v=qiqPOS7ynsA

**予想された動作**
速力が落ちる

**環境:**
 - OS: 窓
 - バージョン: 色々テストしてみたけど変わりなし

**Comment by Kai-Z-JP** [comment]
正常な動作です。
惰性で走っているときはdeccelerationsの0段目の値に従って減速するため、その値が0であると一切減速されません。
0段目の減速度を0未満に変更していただければ大丈夫です。
(参考までに)デフォルトは0.0002です。

**Comment by PC28K** [comment]
わかりました。ありがとうございます
別の話になる気がしますが、notDisplayCabがfalseの場合 P4までにしてもP5まで操作できたりします。これも仕様でしょうか？

**Comment by Kai-Z-JP** [comment]
仕様です。GUI画面との乖離が発生するので値が有効化されないようにしています。

**Comment by PC28K** [comment]
ありがとうございます～
