### ISSUE TITLE
[BUG]HalogenLightのアイテムでレールをクリックしたらクラッシュ

### ISSUE THREAD

**Issue by Saqliva** [Kai-Z-JP/KaizPatchX#43]
**バグの説明**
別modのブロックでクリックしても特にはクラッシュしないので恐らく競合だと思われます
HalogenLight側の問題の可能性アリ

**再現手順**
動作を再現する手順:
1.REIMAさんのHalogen Light Modの蛍光灯でレールをクリックします
2.クラッシュ

**環境:**
 - OS: Windows10
 - バージョン: 1.0.0~RC1.1
 - 他のMod: HalogenLight、ATSAssist等

**Comment by Kai-Z-JP** [comment]
クラッシュレポートの添付をお願いします。

**Comment by Saqliva** [comment]
すっかり忘れておりました
[crash-2021-05-22_14.17.48-client.txt](https://github.com/Kai-Z-JP/KaizPatchX/files/6526066/crash-2021-05-22_14.17.48-client.txt)

**Comment by Kai-Z-JP** [comment]
調査中

**Comment by Kai-Z-JP** [comment]
6f74705afb07f2d451c6b5effde992e24634ca34 で修正
