### ISSUE TITLE
Instant Crash on Loading

### ISSUE THREAD

**Issue by Martin681** [Kai-Z-JP/KaizPatchX#430]
### Describe the bug

What's The reason of this crash? Ive downloaded and installed the mod that crash shows (See the link in the report) and the same happens. What to do?

### To Reproduce

1. Putting the those mods 2. Staring MC 3.Loading screen and then crashes with (the error report provided bellow)!

### Screenshots

![image](https://github.com/Kai-Z-JP/KaizPatchX/assets/59067005/5ce622fa-8427-4e1c-bfc6-716b7d9cedfd)

### Crash Reports

[crash-2024-04-01_19.46.48-client.txt](https://github.com/Kai-Z-JP/KaizPatchX/files/14826499/crash-2024-04-01_19.46.48-client.txt)

### OS

Windows 10 Professional

### KaizPatchX Version

1.7.1

### Other Mods

None

**Comment by Kai-Z-JP** [comment]
Please try setting the game directory to a location other than the .minecraft directory.

**Comment by Martin681** [comment]
Thanks a lot! It works
