### ISSUE TITLE
Add LinePole from new RTM

### ISSUE THREAD

**Issue by Trollebas** [Kai-Z-JP/KaizPatchX#45]
![изображение_2021-05-27_225905](https://user-images.githubusercontent.com/31930760/119889377-26384980-bf3f-11eb-86db-21d2be0ca195.png)
I suggest porting the main problem that makes RTM on 1.7.10 very uncomfortable. This is the supports of the railway catenary network. At the moment they are represented by four standard supports, which is not very good. I suggest introducing a system similar to RTM GR 1.8.1 - the standard supports remain as they were, but a new icon is added - supports with models. I suggest this icon:
![itemPoleModelled](https://user-images.githubusercontent.com/31930760/119889988-f0479500-bf3f-11eb-871c-8d8bb77d5c06.png)
What it helps with is greater compatibility between 1.12.2 and 1.7.10, so you'll spend less time adapting and publishing a separate version of the 1.7.10 package.

**Comment by Kai-Z-JP** [comment]
![image](https://user-images.githubusercontent.com/42648535/132978166-9205b189-0478-4cf0-850b-3d795d59f51f.png)
