### ISSUE TITLE
[BUG] rail Workbenchのheightが変です

### ISSUE THREAD

**Issue by PC28K** [Kai-Z-JP/KaizPatchX#49]
(#23 から)

オリジナルRTMと動作が変わっているらしいです。
オリジナルならレールモデルの高さはそのまま、バラストのとこだけ上がったり下がったりするんですけど1.2RC1ではレールモデルも一緒に動いています。
もういっかい確認していただきたいです。お願いします

**Comment by Kai-Z-JP** [comment]
把握

**Comment by Kai-Z-JP** [comment]
多分修正

![image](https://user-images.githubusercontent.com/42648535/120926190-e92a3f00-c716-11eb-84ce-880ecb420c97.png)

**Comment by PC28K** [comment]
よいと思います
