### ISSUE TITLE
[BUG]右クリックでレール変更するときにrail Workbenchからの高さが反映されない

### ISSUE THREAD

**Issue by PC28K** [Kai-Z-JP/KaizPatchX#50]
**バグの説明**
右クリックでレール変更するときにrail Workbenchからの高さが変わらない

**再現手順**
https://www.youtube.com/watch?v=fNpTNh4hmGs

**環境:**
 - OS: 窓
 - バージョン: 1.2rc1

**Comment by Kai-Z-JP** [comment]
把握

**Comment by Kai-Z-JP** [comment]
#49と同時に修正
