### ISSUE TITLE
全ての列車で、2両以上連結してノッチを入れると前に動かず後ろにちょっと動いて止まる

### ISSUE THREAD

**Issue by himazinst** [Kai-Z-JP/KaizPatchX#51]
**バグの説明**
タイトルのとおりです。1.1、1.2Rc1で確認済みです。

**再現手順**
1. 列車を連結する
2. 前照灯や車内灯、前後ろを設定しノッチを入れる
3. 前に行かず少し後ろ方向に移動し、停車する

**スクリーンショット**
https://youtu.be/jz487i37p2M

**環境**
 - OS:windows10 pro
 - 他のMod: oemod、Soundlimitextends、brace&Oscillos、fastcraft、竹mod、optifine、駅舎mod

**Comment by Kai-Z-JP** [comment]
調査中

**Comment by Kai-Z-JP** [comment]
把握

**Comment by Kai-Z-JP** [comment]
修正
