### ISSUE TITLE
すべての列車で、カーブにレールが2つ隣接した状態で一つのレールに列車をおいて走らせると、もう一つのレールに列車が移動する

### ISSUE THREAD

**Issue by himazinst** [Kai-Z-JP/KaizPatchX#54]
**バグの説明**
タイトルのとおりです。

**スクリーンショット**
画像
https://cdn.discordapp.com/attachments/801957193834430484/860102310360776744/2021-07-01_19.10.52.png
動画
https://youtu.be/9X_miuP1zp0

**環境:**
 - OS: windows10 pro
 - 他のMod:竹,Aroma backUp,asflaltmod,ATSassistmod,cashiermod bibibocraft,decocraft,emotesmod,fastcraft,flenixcitiescore,intelllinput,om,optifine,rendertweaks,signalcontrollermod,signpicture,駅舎mod

**Comment by himazinst** [comment]
追加事項
1.2RC2で確認

**Comment by Kai-Z-JP** [comment]
1.3以降で修正させて頂きます。
ご報告ありがとうございます。

**Comment by Kai-Z-JP** [comment]
0869462 で修正
