### ISSUE TITLE
[BUG] サーバーが全ての追加パックを読み込んでくれない

### ISSUE THREAD

**Issue by Saqliva** [Kai-Z-JP/KaizPatchX#59]
### Describe the bug

クライアント側は正常に読み込んでいることを確認
サーバーに入ると追加パックで追加された車両やレールがないのでサーバー側が読み込んでいないと予想
Thermosでのみ検証してます

### To Reproduce

1.サーバーに参加(多分ローカルでも良いと思われ)
2.レールや車両モデルの選択画面を表示

### OS

Windows10 2004

### KaizPatchX Version

1.2

### Other Mods

ATSAssist1.5.0 ProjectRed StationsMod WirelessRedstoneCBE Bamboo CustomNPCs HalogenLight UpToDate OE

**Comment by Kai-Z-JP** [comment]
把握

**Comment by Kai-Z-JP** [comment]
https://github.com/Kai-Z-JP/KaizPatchX/suites/3153477729/artifacts/7250961
これでどうでしょうか？

**Comment by Saqliva** [comment]
ありがとうございます
修正確認しました
