### ISSUE TITLE
[BUG] [PORTING FROM FIXRTM] RTM doesn't create CrashReport of model loading on server side.

### ISSUE THREAD

**Issue by anatawa12** [Kai-Z-JP/KaizPatchX#66]
### Describe the bug

サーバーで実行時にモデルロードにエラーが有った際にクラッシュレポートを作成しない。
Port from fixrtm/fixrtm#239, fixrtm/fixrtm#243

### To Reproduce

1. [ModelTrain_CRASHING.json.zip](https://github.com/Kai-Z-JP/KaizPatchX/files/6777981/ModelTrain_CRASHING.json.zip)
をmodsに入れる
1. サーバーで起動する

### Expected behavior

クラッシュする

### Actual Behavior

クラッシュしない

### OS

macOS 11.4

### KaizPatchX Version

a90a704

**Comment by Kai-Z-JP** [comment]
ありがとうございます
ポートしました
