### ISSUE TITLE
[porting from fixRTM] we may not be possible to call ByteBuf#array()

### ISSUE THREAD

**Issue by anatawa12** [Kai-Z-JP/KaizPatchX#76]
### Describe the bug

ByteBuf#array() がByteBufの型によっては呼べないので、クラッシュする可能性があります。同様のクラッシュの経験が1.7.10のmodding時に過去に私もあるため、再現してませんが1.7.10でも発生する可能性があるためissueを作成しました。

### To Reproduce

わかりません

### Crash Reports

https://pastebin.com/U8dup2Lz

_Originally posted by @Dushess in https://github.com/fixrtm/fixRTM/issues/164#issuecomment-822788096_

### OS

ソースより確認

### KaizPatchX Version

466c2b37b86134146e2c5e181fc689f40779816e ソースより確認

**Comment by Kai-Z-JP** [comment]
ありがとうございます。

**Comment by Kai-Z-JP** [comment]
https://github.com/Kai-Z-JP/KaizPatchX/blob/466c2b37b86134146e2c5e181fc689f40779816e/src/main/java/jp/ngt/rtm/network/PacketModelPack.java#L49

全文検索で該当
